### PR TITLE
Landing page html and css

### LINKED ISSUE #2: Header
Create the header for the homepage.

Acceptance Criteria (AC):

- [x] Add basic markup to index.html
- [x] Add the h1 for index.html
- [x] Create a pull request for the above requirements

### LINKED ISSUE #3: Buttons & Functionality
Buttons leading to News/Weather pages underneath header.

Acceptance Criteria (AC):

- [x] Create a div to hold the buttons in index.html
- [x] Create a button for news.html
- [x] Create a button for weather.html
- [x] Add styling for the buttons in styles.css
- [x] Add onclick functionality in index.js
- [x] Create a pull request for the above requirements

### LINKED ISSUE #11: Landing Responsive Checks
Make sure landing page is responsive using CSS

Acceptance Criteria (AC):
- [x] Ensure elements display properly on tablet screens
- [x] Ensure elements display properly on phone screens
- [x] Create a pull request for the above requirements

### LINKED ISSUE #15: Initial Build: Landing
Add base HTML markup and CSS styling to landing page.

Acceptance Criteria (AC):
- [x] Add basic HTML markup to index.html
- [x] Add base styling for the page to styles.css
- [x] Create a pull request for the above requirements

### LINKED ISSUE #33: Localstorage functionality
Add local storage functionality to news or weather page

Acceptance criteria (AC):
- [x] Add functionality to store user data in browser for return
- [x] Add functionality to display that data upon return
- [x] Create pull request for the above requirements

### PR DESCRIPTION
**Pull request by vanessa-flores4**
Updated landing page html and created css for landing page.

### CODE REVIEW

**Comment by vanessa-flores4** [comment]
updated landing.css

**Review by vanessa-flores4 — COMMENTED** [review]
updated html and added css.

**Review by vanessa-flores4 — COMMENTED** [review]
mobile, ipad and tablet responsive

**Review by Spit-ball — CHANGES_REQUESTED** [review]
just add your css into styles.css without overrwriting. you may need to use classes specific to your own html for this.

**Review by KaeliDalton — CHANGES_REQUESTED** [review]
I'm seconding the request to put your styling into the main CSS file instead of a separate one for consistency across the site. The HTML looks good aside from needing to add classes so that you can move the styling to the main sheet instead of a separate one.

**Review by KaeliDalton — CHANGES_REQUESTED** [review]
The newest commit looks good but until you put your styling for the landing page into the main style sheet instead of a separate style sheet, I can't approve these changes.

**Comment by vanessa-flores4** [comment]
I updated the html file and connected to the main CSS file.

**Review by Spit-ball — APPROVED** [review]
Looks all good to me! HTML is clear, CSS is mixed in nicely, and the localstorage is there.

**Review by KaeliDalton — APPROVED** [review]
Looks good!

**Pull request merged**
